name:                hs
version:             0.1.0.0
github:              "kamek-pf/hs"
license:             BSD3
author:              "Bertrand Bousquet"
maintainer:          "b.kamek@gmail.com"
copyright:           "2020 Bertrand Bousquet"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kamek-pf/hs#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
